# Generated by Django 4.0.3 on 2022-04-07 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autopark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autoparkmodel',
            options={'ordering': ('id',), 'verbose_name': 'Autopark'},
        ),
    ]
