# Generated by Django 4.0.3 on 2022-04-07 19:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autopark', '0002_alter_autoparkmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, validators=[django.core.validators.MaxLengthValidator(30), django.core.validators.MinLengthValidator(2)])),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)])),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='autopark.autoparkmodel')),
            ],
            options={
                'verbose_name': 'Car',
                'db_table': 'cars',
                'ordering': ('id',),
            },
        ),
    ]
