# Generated by Django 4.0.3 on 2022-04-07 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import utils.avatar_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{2,30}$')])),
                ('surname', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_]{2,30}$')])),
                ('born', models.DateField()),
                ('avatar', models.ImageField(blank=True, upload_to=utils.avatar_util.AvatarUtils.upload_to)),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^\\+380[\\d]{9}$', 'Invalid phone number ex. +380xxxxxxxxx')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
